backend:
  #name: github # Local
  name: git-gateway # Prod
  branch: 51-page-sur-les-bénéficiaires

publish_mode: editorial_workflow
media_folder: 'static/assets/img'
public_folder: '/assets/img'
show_preview_links: true

collections:
  #Posts (English)
  - name: 'posts-en' # Used in routes, e.g., /admin/collections/news
    label: 'Posts (English)' # Used in the UI
    folder: 'news' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'en.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Top Title', name: 'toptitle', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: 'feature Image', name: 'featureImage', widget: 'image' }
      - { label: 'image', name: 'image', widget: 'image' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          summary: '{{fields.tag}}',
          collapsed: true,
          field: { label: 'tag', name: 'tag', widget: 'string' },
          default:
            [
              'AfricaWeWant',
              'CharterAfrica',
              'CivicTechFundAfric',
              'Democracy',
              'DGTrends',
              'Elections',
              'Governance',
              'Mooc_DEG'
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  #Posts (Français)
  - name: 'posts-fr' # Used in routes, e.g., /admin/collections/news
    label: 'Posts (Français)' # Used in the UI
    folder: 'news' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'fr.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Sur Title', name: 'toptitle', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: "Image d'Aperçus", name: 'featureImage', widget: 'image' }
      - { label: 'image', name: 'image', widget: 'image' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          summary: '{{fields.tag}}',
          collapsed: true,
          field: { label: 'tag', name: 'tag', widget: 'string' },
          default:
            [
              'AfricaWeWant',
              'CharterAfrica',
              'CivicTechFundAfric',
              'Démocratie',
              'DGTrends',
              'Élections',
              'Gouvernance',
              'Mooc_DEG'
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  #Pages (English)
  - name: 'pages-en' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages (English)' # Used in the UI
    folder: 'pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'en.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: 'isPage', name: 'page', widget: 'hidden', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  #Pages (Français)
  - name: 'pages-fr' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages (Français)' # Used in the UI
    folder: 'pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'fr.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: 'isPage', name: 'page', widget: 'hidden', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  #Granted (English)
  - name: 'granted-en' # Used in routes, e.g., /admin/collections/granted
    label: 'Granted (English)' # Used in the UI
    folder: 'granted' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'en.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Project', name: 'project', widget: 'string' }
      - { label: 'image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Url", name: "url", widget: "string" }

  #Granted (Français)
  - name: 'granted-fr' # Used in routes, e.g., /admin/collections/granted
    label: 'Granted (Français)' # Used in the UI
    folder: 'granted' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'fr.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Nom', name: 'name', widget: 'string' }
      - { label: 'Project', name: 'project', widget: 'string' }
      - { label: 'image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Url", name: "url", widget: "string" }